### ISSUE TITLE
changing spaces via the context drop down; should that keep on the same page but just change the space?

### ISSUE THREAD

**Issue by jstrachan** [fabric8-ui/fabric8-ui#1449]
if I'm on the Codebases / Pipelines / Apps / Environments page and switch between 2 spaces I'd have thought the UI should stay on the same space; not always go to the space overview page. Otherwise to switch between 2 spaces when looking at something in the Create site, we have to then navigate to Create then navigate to the tab we were on which feels clunky.

@catrobson does that sound a more natural UX to you?

**Comment by joshuawilson** [comment]
I do like that idea. If I'm planning and I need to add an issue to another space it would be better if the context switcher just switched the context and not my view too. 

I think the question we need to ask (and answer) is this; Why would a use change spaces?

**Comment by jstrachan** [comment]
because you're working on different apps in different spaces and you want to switch between them (either planning / codebases / pipelines / apps / environments)

**Comment by catrobson** [comment]
I like this idea as well, but I think we need to think through what happens if I move over into a user context and then back to a space context.  Let me take a task to do a quick run-through of this so we make sure we have all scenarios/use cases covered for how to handle leaving the user in context as they switch between spaces and users.

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#905
