### ISSUE TITLE
Forge Wizard should display error when Jenkins is not ready

### ISSUE THREAD

**Issue by corinnekrych** [fabric8-ui/fabric8-ui#1742]
1. User create a quickstart using Forge:
2. fabric8-generate forge add-on replies: becasue Jenkins is not up.
```JSON
{
    "results": [
        {
            "status": "SUCCESS"
        },
        {
            "status": "SUCCESS",
            "message": "Added Jenkinsfile to project"
        },
        {
            "status": "SUCCESS",
            "message": "Created git repository: https://github.com/aslakknutsen/test1"
        },
        {
            "status": "FAILED",
            "message": "Failed to find Jenkins URL: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://api.starter-us-east-2.openshift.com/apis/extensions/v1beta1/namespaces/aslak/ingresses. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. User \"aslak@redhat.com\" cannot list extensions.ingresses in project \"aslak\"."
        },
        {
            "status": "SUCCESS",
            "message": "Already created BuildConfig aslak/test1"
        }
    ]
}
```
This is the part that is failing when Jenkins is not up and running https://github.com/fabric8io/fabric8-generator/blob/b8cfdc4df7188aa4d312fc9c7411a307c819d4ed/src/main/java/io/fabric8/forge/generator/kubernetes/CreateBuildConfigStep.java#L286

The UI doesnot display the error message, because it filters the result and display only one of the result (ie: the success one).

To reproduce it, we can return Results.fail("Failed to find Jenkins URL: " + e, e); from last step CreateBuildConfigStep

Relate to root cause https://github.com/fabric8-ui/fabric8-ui/issues/1730

**Comment by jstrachan** [comment]
forge wizard can now work without jenkins (providing you update your tenant)

**Comment by joshuawilson** [comment]
@jstrachan isn't it good to still have this, even after you fixed it. Or are we not using Jenkins?

**Comment by jstrachan** [comment]
@joshuawilson it isn't good to still have this, I have fixed using the Jenkins master and we still no longer use it. 

However this issue is unrelated to the accessing the jenkins master; its related to the fabric8-tenant not creating the user's tenant correctly.

While forge no longer requires communication with the jenkins master or the master to be running to create new apps; it does require the users tenant to be created so that we can discover the URL of where jenkins will be so that we can create the webhook with github. 

This error is that we can't detect where jenkins is going to be when it starts up; usually the Jenkins route in the `aslak-jenkins` namespace is created, now, within 4 seconds of the user logging in. 

I guess this issue shows that fabric8-tenant sometimes doesn't create the tenant? Not 100% sure yet what we should do about this. I guess the user trying to 'Update Tenant' manually might fix this. 

I wonder could you try this command:
```
oc get route -n aslak-jenkins
```
there should be 2 routes for `jenkins` and `content-repository` which are created up front as the user logs in for the first time. 

So I guess we need to raise this against this project https://github.com/fabric8-services/fabric8-tenant/issues to ensure we always keep trying to create tenants if there's some issue. Hopefully we can find in the logs why the `aslak` user wasn't provisioned correctly

**Comment by jstrachan** [comment]
I do wonder if there's a chance the jenkins URL discovery code was looking in the wrong namespace; I just patched the forge back end to make absolutely 100% sure it looks in the jenkins namespace then reports the namespace it was looking in (in case we hit some timing issue of fabric8-tenant).

Also we now throw `io.fabric8.forge.generator.kubernetes.BadTenantException` if we cannot find the Jenkins URL; so that the client side could recommend the user tries to `Update Tenant` to fix the issue. Though I'm hoping we can fix fabric8-tenant to ensure we never hit this in practice

**Comment by aslakknutsen** [comment]
@jstrachan The Response is from Forge. It's what happens when there is an error, regardless of what the error is. The UI Borked on that repsonse which is why the Type error got displayed. This issue alone has very little to do with the Tenant services and more about error handling in the forge wizard. 

The quoted response was the response from forge when I reproduced the 'jenkins url error'.

This issue is older than the removed requirement of having Jenkins master available.

**Comment by jstrachan** [comment]
@aslakknutsen I'm aware the error is from Forge. 

I'm just wondering why Forge would ever not be able to find the Jenkins Route in the tenant's jenkins namespace. We always need to be able to find the Jenkins Route to know the Jenkins URL so we can register the github webhooks - irrespective of whether the jenkins master is up.

I'm just about to release the new forge code that explicitly lists the namespaces it checks for the Jenkins Route - just in case its a forge issue. If not though and there's no Jenkins Route, then the underlying cause of the problem is Tenant Service.

**Comment by aslakknutsen** [comment]
@jstrachan Becasue it used to take 2min+ to get tenant services installed, and this was explicitly attempted to be executed before that happened to reproduce the error... But, it does seem to be looking in 'aslak' and not 'aslak-jenkins'. There is a 'Jenkins' service in that namespace as well, but it doesn't have any Route.

**Comment by jstrachan** [comment]
So I guess we can't reproduce this error any more now right (once the tenants are updated)? As the fabric8-tenant is within a second or so?

**Comment by aslakknutsen** [comment]
@jstrachan Correct. The UI should still handle the general Error response from Forge tho.

**Comment by corinnekrych** [comment]
@aslakknutsen @jstrachan Agreed guys. The UI should handle Forge error and Forge exception, therefore the last PR.
