### ISSUE TITLE
Codebases: Layout problem with "open workspace" dropdown

### ISSUE THREAD

**Issue by ibuziuk** [fabric8-ui/fabric8-ui#1758]
![image](https://user-images.githubusercontent.com/1461122/28417732-6ce06962-6d59-11e7-95eb-e008d19d98c6.png)

**Comment by joshuawilson** [comment]
@ibuziuk what is the problem and what do you expect it to do?

**Comment by ibuziuk** [comment]
@joshuawilson the layout looks broken for me. Previously dropdown with available workspaces was per repository, now it is located in the table header

**Comment by dlabrecq** [comment]
If you refresh the page, the combobox should be rendered in the appropriate row where it belongs.

I did some digging and work-item-widget is overriding the .combobox CSS selector -- it's positioned absolutely and sets the 'top' property. I'm guessing that's why it's at the top of the container.

I'm going to set the specificity of that selector so it won't effect anything else.

**Comment by dlabrecq** [comment]
Fixed by https://github.com/fabric8-ui/fabric8-ui/pull/1775
