### ISSUE TITLE
Modify folder structure of code

### ISSUE THREAD

**Issue by dgutride** [fabric8-ui/fabric8-ui#1786]
The Angular style guide recommends using Folder by Feature structure as the project size increases - https://angular.io/guide/styleguide#folders-by-feature-structure.  As openshift.io grows, grouping a few logically related components will greatly help with quickly locating code to work on.  

I'd recommend we restructure the code the following way:

1) Create two new folders named layout and space
2) Move the following:

- space
  - analyze
  - create
  - plan
  - space-settings
  - space-wizard
 
- layout
  - error
  - about-modal
  - header
  - footer

It's possible we should put things like home, landing-page and getting-started also under layout but this would be a good start to helping logically group things.

**Comment by dgutride** [comment]
Work is complete - see pr #1813.  space-wizard can be moved by @corinnekrych when she feels it is a good time.

**Comment by corinnekrych** [comment]
@dgutride oki I'll take care of moving space-wizard under space. Reading angular style, I think we should use `/app/space/wizard` and `app/space/settings` instead of space-wizard as the folder name already have the space context information.

"Why? A developer can locate the code and identify what each file represents at a glance. The structure is as flat as it can be and there are no repetitive or redundant names."

**Comment by dgutride** [comment]
@corinnekrych  - I agree about space-settings and space-wizard dropping the space- prefix.  I didn't want to do that in the first checkin to simplify the more complicated move.  If you want to change settings, let me know, otherwise I'll take care of it later on.

**Comment by joshuawilson** [comment]
That does make sense.
