### ISSUE TITLE
Add a specific page where token can be retrieved after login

### ISSUE THREAD

**Issue by jeffmaury** [fabric8-ui/fabric8-ui#1827]
In order to tools (DevStudio/JBossTools) to integrate the auth phase, the landing page should allow for easy tokens retrieval (like OpenShift does).
So it would be nice if there will be a landing page where tokens can be easily retrieved. Provision for status should also be added.
Page could be:

- a JSON one with well defined fields
- an HTML one (like OpenShift) with well defined div for fields retrieval

**Comment by alexeykazakov** [comment]
This actually can be a standalone page in openshiftio app instead of fabric8-ui so DevStudio can use our login endpoint directly: api.openshift.io/api/login/authoriz?redirect=https://openshift.io/some-new-page
So after login the browser will be redirected to that page and the page just needs to get the token from URL and render it.

**Comment by jeffmaury** [comment]
So what is the Github repo so that I can move this issue

**Comment by joshuawilson** [comment]
@jeffmaury it would go in https://github.com/openshiftio/openshift.io

**Comment by jeffmaury** [comment]
Closed as replaced by openshiftio/openshift.io#466
